# Generated by Django 3.0.14 on 2021-08-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updata_ap',
            new_name='update_at',
        ),
    ]
