# Generated by Django 3.0.14 on 2021-08-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_auto_20210816_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post_set',
        ),
        migrations.AddField(
            model_name='post',
            name='tag_set',
            field=models.ManyToManyField(to='instagram.Tag'),
        ),
    ]
